### ISSUE TITLE
Error on picolisp-repl

### ISSUE THREAD

**Issue by borgauf** [flexibeast/picolisp-mode#2]
I get this whenever I try to do anything with the M-x picolisp-repl started repl:

eldoc error: (file-missing Opening input file No such file or directory /usr/share/doc/picolisp/refN.html)

It jumps to some odd error buffer as well. Same if I try to start the picolisp-mode. I'm on 26.1

**Comment by flexibeast** [comment]
So does the file `refN.html` exist in `/usr/share/doc/picolisp/`? If not, where is `refN.html` located on your system?

**Comment by borgauf** [comment]
I installed picolisp from the Ubuntu repository, i.e., 18.6. But in
that /usr/share/doc/picolisp/ directory there is no ref_.html. I'm trying
to use this with Emacs 26.1, BTW.

**Comment by flexibeast** [comment]
Are there *any* HTML docs in that directory? If not, does Ubuntu have a separate package for the Picolisp documentation?

**Comment by borgauf** [comment]
Why don't I try to do some emacs -q investigating and I'll get back to you.
If you don't recognize this issue, it might be I have something interfering.

**Comment by borgauf** [comment]
Just did a clean boot of emacs (only picolisp-mode installed) and got the
same problem. Actually, my /usr/share/doc/picolisp/ directory has an
additional subdirectory doc, and yes, inside /usr/share/doc/picolisp/doc is
a refN.html. What is calling this?

**Comment by flexibeast** [comment]
ElDoc is the caller, as per your original message; it's trying to locate the PicoLisp documentation so that it can be displayed whilst one is editing PicoLisp.

Do you still get the error if you change the value of `picolisp-documentation-directory` to "/usr/share/doc/picolisp/doc"?

**Comment by gcentauri** [comment]
I experienced this error as well after switching some directories around.  I was wondering about adding a check so that if the documentation directory isn't found, Eldoc will be toggled off so that this strange behavior doesn't happen.  I was quite confused when just navigating through the buffer put me in some strange blank error buffer.

It definitely goes away if the documentation directory can be found (or you toggle off Eldoc mode)

**Comment by flexibeast** [comment]
@gcentauri: Yeah, i noticed this whilst working on something else, and hadn't yet got around to addressing it - sorry! i've just pushed some changes to handle this; could you please let me know if they work for you?

**Comment by gcentauri** [comment]
This does work for me.  I got a popup asking if I wanted to turn off eldoc mode. I would consider just automatically turning off eldoc mode (i believe it is buffer local, and won't affect other modes that use it), and then printing the "no documentation directory found, please check the value of the picolisp-documentation-directory variable" message in the minibuffer.  Or the other way around, don't turn on Eldoc unless the directory is found.

**Comment by flexibeast** [comment]
Yeah, answering 'Yes' to the question makes use of the buffer-locality:

    (if (y-or-n-p "Documentation not found. Turn off Eldoc mode in this buffer? ")
        (eldoc-mode 0))

`picolisp-mode` doesn't turn on `eldoc-mode` itself; as such, it respects the user's existing configuration. (On my system, outside of `picolisp-mode`, i've enabled `global-eldoc-mode`, so that `eldoc-mode` is on by default.) So the "don't turn on Eldoc unless the directory is found" option isn't applicable.

i'd prefer not to disable `eldoc-mode` without the user getting a very noticeable indication that this has happened. Messages displayed in the echo-area can be very quickly overwritten, such that a user might find Eldoc "not working" without having seen an explanation of why. The popup avoids this, and even if it was just an info popup (e.g. "Unable to find documentation; disabling eldoc-mode"), the user would still have to click a button to clear the popup anyway.

My thought was that the current popup gives the user the option to correct the value of the `picolisp-documentation-directory` variable, answer "No" to the popup, and then continue with Eldoc now working. However, i can imagine that if one is in a situation where the documentation is *never* going to be available, having to deal with this popup every time one edits a PicoLisp file would be irritating; are you in that situation?

**Comment by flexibeast** [comment]
(Well, the popup is modal, so i should have written that the user would answer "No", *then* correct the value of `picolisp-documentation-directory`, *then* go back to working on the source.)

**Comment by gcentauri** [comment]
that all makes sense.  i was thinking of the situation where it may never be available (which would be pretty uncommon for picolisp, now that i think of it.  running with out the docs directory somewhere breaks the pil help functions too).  i just didn't like the thought of having to click it for every single picolisp buffer i opened if i happened to be in a situation where i couldn't provide a docs directory.

**Comment by flexibeast** [comment]
\*nod\* Fair enough! i've now added a `picolisp-documentation-unavailable` defcustom to handle that situation; does that work for you? If so, i think i'll close this issue, and @borgauf can reopen it if the initial problem still isn't resolved for them.

**Comment by gcentauri** [comment]
👍
